### ISSUE TITLE
gluefactory

### ISSUE THREAD

**Issue by Mr-ZhuJun** [facebookresearch/vggsfm#1]
http://mirrors.i.brainpp.cn/pypi/simple/gluefactory/

Hello, thank you for your open source work!
Currently, during my own use, I discovered that the gluefactory library kept reporting the following error after pip installation.

ModuleNotFoundError: No module named 'gluefactory'

**Comment by jytime** [comment]
Hi @Mr-ZhuJun ,


Could you please have a try on the code below? I can update this in install.sh


```
# install gluefactory
git clone --recursive https://github.com/cvg/glue-factory dependency/glue-factory
cd dependency/glue-factory/
python -m pip install -e .  # editable mode
cd ../../

```

**Comment by jytime** [comment]
I just rerun the install.sh by myself. It should work now. Feel free to comment if something looks incorrect.

**Comment by jytime** [comment]
Hey I will provide the code to do this today or tomorrow. Basically, you just need to change this part to build your own dataset

https://github.com/facebookresearch/vggsfm/blob/86736a0ce2475a273ee8b59dbed4924d0dd0e7ff/vggsfm/datasets/imc.py#L59-L102
