### ISSUE TITLE
pytorch3d error

### ISSUE THREAD

**Issue by 1511607288** [facebookresearch/vggsfm#11]
Hi, I already installed pytorch3d 0.7.5, but when i run demo.py or test.py, it still showed that "ModuleNotFoundError: No module named 'pytorch3d'".I really dont know how to fix it.
Thanks for your help!
![erro](https://github.com/facebookresearch/vggsfm/assets/53338107/5a3aba06-67a1-4ff5-8b09-7c5a259fd802)

![erro2](https://github.com/facebookresearch/vggsfm/assets/53338107/ea620235-ab8e-4306-a784-61aee9415751)
pytorch3d 0.7.5 installed at the bottom of the picture

**Comment by AshkanFeyzollahi** [comment]
try running demo with this command

```bash
py -V:3.10 path/to/demo.py
```

**Comment by jytime** [comment]
Hi, 

Could you please have a try on using conda and our provided script(https://github.com/facebookresearch/vggsfm/blob/main/install.sh)?

**Comment by 1511607288** [comment]
> try running demo with this command
> 
> ```shell
> py -V:3.10 path/to/demo.py
> ```

Thank you for your advice, i tried but still the same. Finally i reinstalled it in ubuntu instead of windows...it still has some bugs but not about pytorch3d any more.
Have a good day!

**Comment by 1511607288** [comment]
> Hi,
> 
> Could you please have a try on using conda and our provided script(https://github.com/facebookresearch/vggsfm/blob/main/install.sh)?

Thank you for your advice, and that is exactly what i did in ubuntu instead of windows...it still has some bugs but not about pytorch3d any more.
Have a good day!

**Comment by jytime** [comment]
Hi @1511607288 great I closed this issue now. Feel free to reopen this if you need more helps
