### ISSUE TITLE
reconstruction with shared camera model

### ISSUE THREAD

**Issue by yuanxy92** [facebookresearch/vggsfm#17]
Thanks for your great work! Now I use one camera to capture images and I want to reconstruction the scene with a shared camera model, How to set the VGGSfM?

**Comment by jytime** [comment]
Sorry for the late update. Camera model sharing has been enabled now, as in 5af688c87f5b6105ceb9f4e422cb2b4bd45ee19a. You can simply enable it by ```shared_camera=True```.
