### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bhack** [facebookresearch/vggsfm#18]
Can you clarify the repository license.

I see a lot of source files under BSD but the license file seems to claim something different.

Thanks

**Comment by jytime** [comment]
Hi,

This repository follows a CC-NonCommercial license. I will update the source files to avoid confusion.

We hope to re-license this to allow Commercial  usage in the future but cannot promise it.

**Comment by FreakTheMighty** [comment]
@jytime ant updates on the prospects for a license that permits commercial uses?
