### ISSUE TITLE
raise index error when use my own dataset

### ISSUE THREAD

**Issue by Tonsty** [facebookresearch/vggsfm#19]
the error message is as follows, the dataset has 12 images in total

error executing job with overrides: ['SCENE_DIR=examples/220000000022460404_0', 'query_frame_num=5', 'max_query_pts=1600']
Traceback (most recent call last):
  File "/data1/easonyztang/vggsfm/demo.py", line 117, in demo_fn
    predictions = run_one_scene(
                  ^^^^^^^^^^^^^^
  File "/data1/easonyztang/vggsfm/demo.py", line 303, in run_one_scene
    BA_cameras_PT3D = BA_cameras_PT3D[center_order]
                      ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/data1/easonyztang/vggsfm/minipytorch3d/cameras.py", line 424, in __getitem__
    raise IndexError(f"Index {max(index)} is out of bounds for select cameras")
IndexError: Index 11 is out of bounds for select cameras

**Comment by jytime** [comment]
Hi,

This should have been fixed in the recent commits. Can you pull the repo and run it again, or try our hugging face demo?
