### ISSUE TITLE
How to run on own dataset? 

### ISSUE THREAD

**Issue by kk6398** [facebookresearch/vggsfm#2]
How to run on own dataset and get the output file as colmap.  

For example, I want to test the vggsfm on the mipnerf360, and then test the performance of 3D gaussian splatting after obtaining the output file as colmap.

**Comment by jytime** [comment]
Hi,
 
You can do it by [demo.py](https://github.com/facebookresearch/vggsfm/blob/main/demo.py), which is configured by `cfgs/demo.yaml`. Please feel free to let me know if you meet any problems during this process. If the result looks weird, you can attach the images here and I will be happy to debug for you. 

Best,
Jianyuan

**Comment by kk6398** [comment]
Hi, thank you for your reply. I tried to implement the method you provide, but I met some questions: 1) Is it necessary that the format of file be .png. Because the mipnerf360 and llff dataset provide the .jpg format.  
2) I met the OOM problem when I run the code "python demo.py" or "CUDA_VISIBLE_DEVICES=1 python demo.py" on one 4090GPUs or one 4090GPU. The OOM as follow:
![image](https://github.com/facebookresearch/vggsfm/assets/70420660/eb295005-6f6c-4588-b127-94a4402bf5ef)

**Comment by kk6398** [comment]
> Hi, thank you for your reply. I tried to implement the method you provide, but I met some questions: 1) Is it necessary that the format of file be .png. Because the mipnerf360 and llff dataset provide the .jpg format. 2) I met the OOM problem when I run the code "python demo.py" or "CUDA_VISIBLE_DEVICES=1 python demo.py" on one 4090GPUs or one 4090GPU. The OOM as follow: ![image](https://private-user-images.githubusercontent.com/70420660/329435744-eb295005-6f6c-4588-b127-94a4402bf5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDc4MzIsIm5iZiI6MTcxNTMwNzUzMiwicGF0aCI6Ii83MDQyMDY2MC8zMjk0MzU3NDQtZWIyOTUwMDUtNmY2Yy00NTg4LWIxMjctOTRhNDQwMmJmNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAyMTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NTc2ZDY5MmQwNzYyZGM0MjA3NjE5YjUzM2ZiMWU1NTEyNmU4YTE4MmI4ZTA2MGQ5OTNmYmQ1MjNjYWRhNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LlPj1EuWqa639VQekmYYI-UhbuaAx3xFFRKtjmDRWE0)

The number of llff and minerf360 is 20 and 150, respectly.

**Comment by jytime** [comment]
Hi @kk6398 ,

- Both jpg and png are okay. 
- 4090 should at least be oaky for the setting of 20 frames. Can you check what would happen if reducing cfg.max_ransac_iters to 2048?

**Comment by kk6398** [comment]
Hi, I try change the parameters you said.   And final successful condtion, I reduce to 14 frames of llff_fern dataset (resolution: 4032x3024),  and reduce cfg.max_ransac_iters to 2048.            The memory costs 22G.

**Comment by jytime** [comment]
ah I got it. This may be because because llff is too high resolution (4032x3024), but our program should have already resized it to 1024x1024. I will check the code this weekend to see if there is any leakage.

**Comment by jytime** [comment]
Hi @kk6398 ,

By the way, instead of reducing the image number (which is not wanted in most time), you can further reduce max_ransac_iters. It would be safe enough to reduce max_ransac_iters to 1024 or 512. 

At the same time, I have quickly updated an EfficientCorrBlock. If necessary, you could set cfg.MODEL.TRACK.efficient_corr as True. It will further reduce GPU usage but may affect the performance slightly. 

https://github.com/facebookresearch/vggsfm/blob/f490bc11b3eb68c1aa832fcd2e230ffacbf575fd/cfgs/demo.yaml#L21

**Comment by kk6398** [comment]
I try the methods including "reduce max_ransac_iters to 1024 or 512 even 128" and "efficient_corr: True". However, it is useless unfortunately.

By the way, do you try to finish the downstream application such as 3DGS or nerf using the output file(cameras.bin   images.bin   points3D.bin).  There is a litte difference with colmap (point3D.ply).  And I haven't finish the 3DGS recontruction. The bug is as follow:

![image](https://github.com/facebookresearch/vggsfm/assets/70420660/d11d77b3-2bb7-442c-b409-7e19802ebadb)

**Comment by jytime** [comment]
I tried it on nerf before but not 3DGS. Which codebase are you using? The output files of cameras.bin images.bin points3D.bin are the standard output of the sparse reconstruction from colmap. They should support it. Or do you need a cameras.txt, images.txt and points3D.txt?

**Comment by jytime** [comment]
This may be a related question? https://www.reddit.com/r/GaussianSplatting/comments/17gatms/properly_generate_ply_file_for_3d_gaussian/

**Comment by jytime** [comment]
Hi @kk6398 

We can also support grouping/filtering images like COLMAP, but it seems it is not the key problem. The problem you met above is some files are missing right? It seems image_13 is not provided in the folder but stored in the reconstruction output. Can you double check if all files exist and their names match?

![image](https://github.com/facebookresearch/vggsfm/assets/37647961/67a36c8a-7408-4e9d-9ce1-794d3c58653e)

**Comment by kk6398** [comment]
Got it.  I change the name in ./images to imgae_0, image_1 .... image_13.      And it cannot end in ”.jpg“ ( image_0 instead of image_0.jpg) . Because I try the image_i.jpg, which doesn't work.
It seems like wired. The colmap output files don't change the original image name.

![image](https://github.com/facebookresearch/vggsfm/assets/70420660/933c526b-1a95-488e-9130-d715f6af4eb5)

![image](https://github.com/facebookresearch/vggsfm/assets/70420660/8381ccb4-3a53-404f-b79b-6117be0ebdbe)

**Comment by bhack** [comment]
Can we add a small section about this to the Readme?

**Comment by jytime** [comment]
Hi @bhack and @kk6398 ,

I have upgraded the repo to v2 and added a detailed instruction on how to run on your own data. At the same time, this version should only take around 30% to 50% GPU memory as before. If you still have interest, please let me know if it works for you or now.
