### ISSUE TITLE
Regarding the impact of image sizes on GPU memory.

### ISSUE THREAD

**Issue by Yms0101** [facebookresearch/vggsfm#22]
During the experimental process, when dealing with certain cases, I reduced the image sizes; however, the GPU memory usage did not decrease significantly. Strikingly, in some instances, decreasing the image size led to an unexpected surge in memory consumption. Could you explain the reasons behind this phenomenon? Additionally, I would appreciate your insights into how altering image dimensions might affect the final results.

**Comment by jytime** [comment]
Hi @Yms0101 ,

May I ask, when you decreasing the image size, did you change the flag ```img_size``` or directly resized the input images? In our current script, all the input images will be resized to ```img_size```, e.g., 1024x1024. If you resized input images, e.g., by half, it will lose the details but using the same mem for computation. 

And, for generalisation, I would not recommend to reduce ```img_size```. The better way is to reduce ```max_query_pts``` or ```query_frame_num```. We default ```max_query_pts``` as 4096, but usually 2048 or even smaller should work very well.

If these does not solve your problem, feel free to send your images to me. 

Best,
Jianyuan

**Comment by jytime** [comment]
by the way, please ensure to git pull from our latest version

**Comment by Yms0101** [comment]
Thank you for your response. I adjust the image_size parameter. It appears that reducing the imag_size may not have a substantial impact on the final GPU memory usage.
