### ISSUE TITLE
About visualization tool

### ISSUE THREAD

**Issue by wooni-github** [facebookresearch/vggsfm#26]
I am truly grateful for the exceptional work you have done. 

If it is not too much trouble, may I kindly inquire about the software or library you used to create the visualizations for Figures 1, 2, and 4 in your paper? I often come across similar images featuring sky-blue points and yellow arrows to depict camera poses, and I am very interested in learning how to achieve such visualizations.

**Comment by jytime** [comment]
Hi @wooni-github ,

They were generated using the Cycles renderer from [Blender](https://github.com/blender/blender)

**Comment by bluestyle97** [comment]
@jytime Hi, could you please kindly provide the blender rendering script for visualizing camera poses? The figures in your paper are really beautiful!

**Comment by jytime** [comment]
Hi @bluestyle97, thanks for your interest! Unfortunately, this is an internal package and was not developed by me. I also do not have the permissions to share it publicly.
