### ISSUE TITLE
 Two different camera models for capturing images

### ISSUE THREAD

**Issue by kke19** [facebookresearch/vggsfm#27]
HI, 

Thank you very much for your work, it has been very helpful to me.

In my dataset, I use two different camera models for capturing images. I would like to know if the current version of VGGSFM supports this type of data. If it does, could you please provide guidance on how to proceed?

Thank you!

**Comment by jytime** [comment]
Hi @kke19 , no worries it should work well. The method assumes a separate camera for every frame.

**Comment by kke19** [comment]
Hi,

Following up on my previous inquiry regarding the alignment issue between two different cameras with distinct sensor sizes. One camera has a sensor size of 4056x3040 pixels (middle row camera), while the other is 3648x5472 pixels. This disparity in sensor sizes is causing alignment challenges between images.
Could you provide insights or methods for handling scale differences between images captured by these cameras?
I would appreciate any advice on adjusting parameters or setting to achieve better alignment results.

Here is my current reconstruction.
![截图 2024-07-18 10-25-35](https://github.com/user-attachments/assets/f07835db-d108-4e4a-93f6-59080287cb61)
![截图 2024-07-18 10-26-04](https://github.com/user-attachments/assets/fb19db38-72fe-428e-bc65-4ceb68174118)
![截图 2024-07-18 10-26-17](https://github.com/user-attachments/assets/c9c79fcb-3147-4e07-a808-32ba11a67ed4)
![截图 2024-07-18 10-26-35](https://github.com/user-attachments/assets/f9e4ca42-6d42-42af-9abf-a3dbedf4dcb1)

Here is my current parameters.
![图片](https://github.com/user-attachments/assets/fc3cc420-7afd-45ee-b115-3034acb3efc0)
![图片](https://github.com/user-attachments/assets/a6101dba-d5ad-4c84-82b6-1dedd833f018)
![图片](https://github.com/user-attachments/assets/735cd68d-9353-4949-b926-0a91ecebbeda)

If possible, could you please provide an email address where I can share more detailed raw data for further analysis?

**Comment by kke19** [comment]
By the way, this is the correct position when we run colmap。
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=6801159745959625068 skey=@crypt_749cd3ba_79377b3c83a611d27820a597843bccc3 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/7ac18206-535c-4342-84b1-030aecd2dd35)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=102203428859428677 skey=@crypt_749cd3ba_79377b3c83a611d27820a597843bccc3 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/e1f67183-3710-4d75-bba1-78e1b40f2b0d)

**Comment by jytime** [comment]
It should not be a problem. Please feel free to send the images to my email.
