### ISSUE TITLE
Does not produce correct solution

### ISSUE THREAD

**Issue by nickponline** [facebookresearch/vggsfm#28]
I tried a simple ring of 30 images. Here's the link https://www.dropbox.com/s/o4hneo8h295f9wn/images.zip?dl=0

But I get this double result.
![image](https://github.com/user-attachments/assets/d971ea65-a60e-4564-98aa-a7c1e4b2e5e0)

Other SFM libraries process it successfully. Are there settings I should change?

**Comment by jytime** [comment]
Hi Nicholas,

Can you try:

```
python demo.py SCENE_DIR=/YOUR/PATH query_frame_num=4 max_query_pts=2048
```

It gives me something like this:

<img width="392" alt="Screenshot 2024-07-20 at 09 17 09" src="https://github.com/user-attachments/assets/ec19ccad-a0f4-460b-9906-dd713350b88e">


<img width="1022" alt="Screenshot 2024-07-20 at 09 15 14" src="https://github.com/user-attachments/assets/9bd21599-16a7-4de0-b00c-cd7edccce054">

**Comment by nickponline** [comment]
Thank you!
