### ISSUE TITLE
Triton Incompatibility

### ISSUE THREAD

**Issue by Fanie-Visagie** [facebookresearch/vggsfm#30]
At a loss...everything is installed yet I cant get around this: 

(splats) D:\vggsfm>python demo.py SCENE_DIR=data
Poselib is available
Poselib is available
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\ProgramData\miniforge3\envs\splats\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'

**Comment by jytime** [comment]
Hi this seems because you are using a windows machine. The install env was prepared for linux and not tested in windows.

According to the errors, it seems xformers does not work correctly. As guided in https://github.com/facebookresearch/xformers, probably you can try:

```
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
```

to install xformers for window manually.

**Comment by Fanie-Visagie** [comment]
I have come absolutely full circle...has taken me the whole day and still getting nowhere...for some reason, and I dont know what chatgpt made me install...the result for all python is now: (models) D:\03 Innovation\vggsfm>python demo.py SCENE_DIR=data resume_ckpt=checkpoints
*** Aborted at 1721646288 (unix time) try "date -d @1721646288" if you are using GNU date ***
    @     0x7fffb6554172 log2f
    @     0x7ff7c6de1f5c OPENSSL_Applink
    @     0x7fffabffe5cf __C_specific_handler
    @     0x7fffb8c5504f __chkstk
    @     0x7fffb8bce866 RtlFindCharInUnicodeString
    @     0x7fffb8c5403e KiUserExceptionDispatcher
    @     0x7fff9214264e void __cdecl __ExceptionPtrRethrow(void const * __ptr64)
    @     0x7ffe348d8ebe public: void __cdecl c10::ivalue::Future::markCompleted(void) __ptr64
    @     0x7ffe34c683a2 struct _object * __ptr64 __cdecl THPGenerator_initDefaultGenerator(struct at::Generator)
    @     0x7ffe2b26dea5 (unknown)
    @     0x7ffe2b7c6b29 PyInit_pycolmap
    @     0x7fffac2b4160 __CxxFrameHandler4
    @     0x7fffac2b2572 (unknown)
    @     0x7fffb8c54896 RtlCaptureContext2
    @     0x7ffe2b2709b9 (unknown)
    @     0x7fff15eb24ed PyCFunction_GetFlags
    @     0x7fff15e6dee8 _PyObject_MakeTpCall
    @     0x7fff15e77261 PyComplex_AsCComplex
    @     0x7fff15eb6c74 _PyObject_GenericGetAttrWithDict
    @     0x7fff15eb65b8 PyObject_GetAttr
    @     0x7fff15eb6209 PyObject_GetAttrString
    @     0x7ffe2b2a609e PyInit_pycolmap
    @     0x7ffe2b2fdc6d PyInit_pycolmap
    @     0x7ffe2b2d651d PyInit_pycolmap
    @     0x7ffe2b294170 (unknown)
    @     0x7ffe2b2a0a48 PyInit_pycolmap
    @     0x7ffe2b2a054e PyInit_pycolmap
    @     0x7fff15fa7a5b _PyImport_GetModuleAttrString
    @     0x7fff15fa732c PyImport_Import
    @     0x7fff15fa3cea _Py_hashtable_destroy
    @     0x7fff15eb20f9 PyCFunction_GetFlags
    @     0x7fff15f76dec PyEval_GetFuncDesc

hahaha....looks like a format is in order >_<

**Comment by Fanie-Visagie** [comment]
A pity, for what you have done here is SOOO fundamentally important for GS and Nerf Models...

**Comment by jytime** [comment]
Sorry that I don't have a Windows machine, and hence can't test it for you. Maybe one day we'll try to integrate our approach into the existing nerf/gau codebases.

**Comment by Fanie-Visagie** [comment]
Such a pity. Tried your demo with 100 pictures and can see it is capped.

Again, what you have done here is revolutionary, especially for gs implementation.

Will see what I can do about learning Linux and wsl as this is such an important part of the workflow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
