### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by luoshuiyue** [facebookresearch/vggsfm#31]
why I get this error when run demo.py:
![1721632014677](https://github.com/user-attachments/assets/ebb09485-4385-4f68-ac54-8b98055bad83)

**Comment by jytime** [comment]
Hi,

This does not show where the error is. Can you type ```exprt HYDRA_FULL_ERROR=1``` in you terminal and rerun the demo.py again?

**Comment by luoshuiyue** [comment]
I set HYDRA_FULL_ERROR=1,then run the command again:
![1721720614883](https://github.com/user-attachments/assets/be6183a7-f03a-405b-8de3-6e6e9066e209)

**Comment by jytime** [comment]
Hi this seems your downloaded file is not complete. 


Check this post for more details: 
https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory

**Comment by surabhi96** [comment]
Hi @jytime thanks for the amazing work! I was getting a similar error. This is my o/p after setting `export HYDRA_FULL_ERROR=1`. Also, seems like there was no convergence. I also get the following warning before the BA routine. Not sure if it's relevant but posting it as well. Thanks!
![image](https://github.com/user-attachments/assets/0b149962-4006-4cb1-80af-615645f804e6)
![image](https://github.com/user-attachments/assets/a55a2db5-4651-49a6-a9f3-f9d3cd536127)

**Comment by jytime** [comment]
oh this seems all the frames are filtered out due to 

https://github.com/facebookresearch/vggsfm/blob/46570ccfc4978e485f3a0a2e33483e243face9de/vggsfm/runners/runner.py#L496-L509

Can you try to set filter_invalid_frame=False and see the results?

**Comment by surabhi96** [comment]
Thanks for your prompt reply! I don't get errors anymore but seems like there is still no convergence? For reference, I am feeding it 10 sequential images with a linearly moving camera with enough overlap between images i.e. the translation between two camera positions would be about 10 cm. 
![image](https://github.com/user-attachments/assets/66cfb5f4-3277-4089-a854-6ec19ffa3f34)

**Comment by jytime** [comment]
Hey @surabhi96 

No convergence is okay here because it shows the optimisation result for last BA. A final cost of 0.18 seems not bad here. You can visualize the results by gr_visualize=True.

If it still does not work, feel free to send the images to me.
