### ISSUE TITLE
Color Value Not Saved When Saving Reconstructed Points3D with Pycolmap

### ISSUE THREAD

**Issue by hwanhuh** [facebookresearch/vggsfm#32]
First of all, thank you for conducting and publishing this great study.

I've encountered a small error: the color value is not saved when saving reconstructed points3D with pycolmap.
This problem can be resolved by using plyfile to save points3D.ply as shown below.

**Solution:**

1. Define a function to save the PLY file:

```python 
from plyfile import PlyData, PlyElement
import numpy as np

def storePly(path, xyz, rgb):
    dtype = [('x', 'f4'), ('y', 'f4'), ('z', 'f4'),
             ('nx', 'f4'), ('ny', 'f4'), ('nz', 'f4'),
             ('red', 'u1'), ('green', 'u1'), ('blue', 'u1')]

    normals = np.zeros_like(xyz)

    elements = np.empty(xyz.shape[0], dtype=dtype)
    attributes = np.concatenate((xyz, normals, rgb), axis=1)
    elements[:] = list(map(tuple, attributes))

    vertex_element = PlyElement.describe(elements, 'vertex')
    ply_data = PlyData([vertex_element])
    ply_data.write(path)
```
2. Use the storePly function in demo.py at [line 150](https://github.com/facebookresearch/vggsfm/blob/ebb7489ef9a9009e9965f531efad566abe3baa2a/demo.py#L148):

```python
storePly(os.path.join(output_path, "points3D.ply"), predictions["points3D"].clone().cpu().numpy(), predictions["points3D_rgb"].clone().cpu().numpy() * 255)

```

**Comment by jytime** [comment]
Thanks for pointing out this! I will check if we can easily save the colors to pycolmap reconstruction file. If not, we can store the rgb files to a separate file as you suggested.

**Comment by jytime** [comment]
Hi,

I made a quick fix to save the point rgb color to colmap reconstruction object. Please feel free to let me know if it does not work for you.

https://github.com/facebookresearch/vggsfm/commit/25ec3e83c6a53b14cc86a77dee8fcc7267d158b3
