### ISSUE TITLE
Extension to large number of images?

### ISSUE THREAD

**Issue by crepejung00** [facebookresearch/vggsfm#33]
Hi, 
Regarding the bundle adjustment process during inference time, I understand the large memory consumption resulting in OOM when handling more than 30 images with a single A 100 GPU. 
Can this architecture be extended to scenes consisted of unordered set of 200 images or more such as MipNeRF360 dataset?

Thanks.
Best regards,
Jaewoo.

**Comment by Fanie-Visagie** [comment]
Happy to provide a sample dataset of a telecom tower (thin green structure with a green field background) to test....really would like to get something better than COLMAP into play....

I have installed Linux to process this library...and with a few images, it is proving MUCH better than colmap.

**Comment by hwanhuh** [comment]
Reduce img_size, max_query_pts, and query_frame_num will help. 
With max_quert_pts = 1 and query_frame_num  = 512, I successfully run vggsfm over 90 images in a single RTX4090.

**Comment by jytime** [comment]
Hi, for an 80G A100, it should be able to process >120 images. If you are using an 40G A100, it should also not be a problem to process 30 images. Can you share your setting or images, and hence I could have a look?

We are developing a version to support 500 or more images. It is a bit delayed but we do hope to share it soon.

**Comment by jytime** [comment]
> Reduce img_size, max_query_pts, and query_frame_num will help. With max_quert_pts = 1 and query_frame_num = 512, I successfully run vggsfm over 90 images in a single RTX4090.

Hi, I just uploaded a commit. Now you can run 90 images regardless of the size of ```query_frame_num```. This means ```query_frame_num``` will only affect the processing time, not the GPU memory usage.

By the way, I guess you meant query_frame_num=1 and max_query_pts=512 above?

**Comment by hwanhuh** [comment]
@jytime thx!
oh, yes. I flipped :)

**Comment by crepejung00** [comment]
Thanks everyone for the kind explanation! 
I will now close the issue.

Best regards,
Jaewoo.

**Comment by jytime** [comment]
Hi,

Now we can process at most 400 frames once. Feel free to have a try
