### ISSUE TITLE
Multiple cameras?

### ISSUE THREAD

**Issue by antithing** [facebookresearch/vggsfm#34]
Hi! Would this code work for different cameras in the same dataset? 

Eg, image 1,2,3 from camera 1
Image 4,5,6 from camera 2 (different intrinsics)

Thanks!

**Comment by jytime** [comment]
Hi, 

It is not a problem. As long as you don't set ```shared_camera``` as True, the framework will optimize a separate camera for each frame.

**Comment by antithing** [comment]
Thanks! One more question, what format are intrinsics calculated in? Just focal length? Or fx,fy,cx,cy and distortion matrix?

**Comment by jytime** [comment]
I would suggest to start from camera_type: "SIMPLE_PINHOLE", i.e., formulated as f, cx, cy. Although we also support camera_type: "SIMPLE_RADIAL", i.e., f, cx, cy, distortion, it has some known issues there and I am going to fix it.
