### ISSUE TITLE
Workflow for 360 imagery?

### ISSUE THREAD

**Issue by piotrekp357** [facebookresearch/vggsfm#35]
Hi! Awesome work! The results I'm getting with the "perspective" images are pretty great so far! I wanted to ask if it's possible to make it run on the equirectangular 360 images? I was thinking that it might be a matter of splitting 360 deg images into sets of overlapping perspectives (with known fov and virtually no lens distortion), but after initial tests, it looks like I'd need to apply some positional constraints. Maybe it's possible to use the georeferenced images to "guide" the reconstruction?

**Comment by jytime** [comment]
Hi,

Yes, it is definitely better if you have some geo information. I guess it can work in the case of "splitting 360 deg images into sets of overlapping perspectives (with known fov and virtually no lens distortion)". If you’d like me to take a look, you can share these overlapping perspectives via email or drop them here.
