### ISSUE TITLE
How to Obtain Correct COLMAP Model

### ISSUE THREAD

**Issue by ktkt2020** [facebookresearch/vggsfm#36]
Hi,
Thanks for sharing your excellent work!

The COLMAP results by running `demo.py` looks a little bit weird. It seems that the 2D points are located in 1024x1024 padded and resized images, but the camera parameters correspond to the original image size.

Here is an example, if we use the original images given in the example, the 2D points visualized in COLMAP are with offsets.
![image](https://github.com/user-attachments/assets/c43241e1-f127-4a65-ab91-960bcbe54679)
If we use 1024x1024 padded and resized images with the following code for visualization, the 2D points are in the correct positions.  https://github.com/facebookresearch/vggsfm/blob/b15f0d86bcd654067ff7a1d00b0cb74574ee83a6/vggsfm/datasets/demo_loader.py#L125-L134
![image](https://github.com/user-attachments/assets/1c998565-8dd4-426b-9a61-a930a1e4d07e)

The same issue exists when viewing the 2D/3D correspondences in COLMAP. It looks like the camera parameters, 3D points, and camera poses are in the same and correct coordinate system, but the 2D points are not.
![image](https://github.com/user-attachments/assets/66748df3-3d64-4aef-810a-325183a714ed)

**Comment by jytime** [comment]
Hi @ktkt2020 ,

Yes this is because the reconstruction was conducted on the padded and resized 1024x1024 images. I converted the camera parameters to the original resolution to enable people to directly conduct NeRF/Gaussian. But I agree this may lead to a conflict when viewing 2D keypoints. **Do you think it is good for you to provide a flag to also convert the 2D keypoints to the original resolution?**

Besides, how do you feel about the results of the reprojection video in ReadMe? Those points come from the reprojection of 3D points instead of 2D keypoints.

**Comment by ktkt2020** [comment]
Thanks for your fast reply!

Adding a flag to convert the 2D key points to the original resolution can help to view the keypoints and reprojection errors easily in COLMAP. Yet it is not necessary for NeRF/Gaussian applications.

The reprojection by setting `make_reproj_video=True` video looks pretty good.

**Comment by jytime** [comment]
Hi @ktkt2020 ,

I’ve pushed an update in the `make_a_package` branch that adds support for converting 2D key points to their original resolution. You can enable this feature by setting `shift_point2d_to_original_res` to True. The code can be found here:

https://github.com/facebookresearch/vggsfm/blob/95f59caeef6fd3cf7b9936d0fb26b1a845ea4d61/vggsfm/runners/runner.py#L427

I’ll integrate this into the main branch soon. Feel free to let me know if this still does not work for you.

**Comment by ktkt2020** [comment]
Hi @jytime,

I've tested your new branch. It works. The 2D points are located in the correct positions. And the final COLMAP model is much more consistent now.

In the kitchen dataset, most reprojection errors of the output COLMAP model are greater than 1 px. Yet the console outputs are smaller (around 0.73 px). I'm not sure if it is related to the 2D keypoints converting. But, this is not a big issue to me.
```
 Initial cost : 0.805735 [px]
   Final cost : 0.734272 [px]
```

![image](https://github.com/user-attachments/assets/807b4c3b-5c52-42d6-ac3e-4eeb930ca60e)

**Comment by jytime** [comment]
Hi @ktkt2020 ,

Thanks for your feedback! Yes I think it is due to the slight mismatch after scale conversion. I would recommend only use this for visualisation.  

Close the issue now. Feel free to reopen if you have some further questions.
