### ISSUE TITLE
Deal with distortion

### ISSUE THREAD

**Issue by yzhang-gh** [facebookresearch/vggsfm#37]
Hi, this work looks amazing. However, I find that it doesn't support distortion. There is an extra `camera_type` `SIMPLE_RADIAL` but the distortion parameter is set to 0.

https://github.com/facebookresearch/vggsfm/blob/b15f0d86bcd654067ff7a1d00b0cb74574ee83a6/vggsfm/utils/triangulation.py#L284-L287

May I ask whether you have some experiences with optimizing the distortion parameters in this framework?

Thanks!

**Comment by jytime** [comment]
Hi,

It means the distortion parameter is initialised as zero, and will be optimised in the BA stage. So the final output will be a SIMPLE_RADIAL model. 

But there is a known issue with camera_type == "SIMPLE_RADIAL". A temporal solution is to comment out these lines.

https://github.com/facebookresearch/vggsfm/blob/b15f0d86bcd654067ff7a1d00b0cb74574ee83a6/vggsfm/utils/triangulation.py#L856-L868

**Comment by yzhang-gh** [comment]
I see. Thank you for the reply.

**Comment by JiamingSuen** [comment]
> Hi,
> 
> It means the distortion parameter is initialised as zero, and will be optimised in the BA stage. So the final output will be a SIMPLE_RADIAL model.
> 
> But there is a known issue with camera_type == "SIMPLE_RADIAL". A temporal solution is to comment out these lines.
> 
> https://github.com/facebookresearch/vggsfm/blob/b15f0d86bcd654067ff7a1d00b0cb74574ee83a6/vggsfm/utils/triangulation.py#L856-L870

@jytime Could you elaborate on this known issue? I'm also interested in optimizing for the distortion parameters. Thanks!

**Comment by jytime** [comment]
Hi @JiamingSuen ,

In the beginning this codebase was only written for simple pinhole camera. So 

1. We currently do not store distortion coefficients after executing batch_matrix_to_pycolmap() or pycolmap_to_batch_matrix(). As a result, these coefficients default to zero after each run of batch_matrix_to_pycolmap, which can lead to inaccuracies. Although our current implementation manages small distortions adequately, storing and reusing these coefficients in each BA cycle would improve accuracy. More specifically, if we comment the code snippet above, the returned pycolmap Reconstruction object will directly use the optimization output from pycolmap, which contains its optimized distortion coefficients. 
2. We did not account for distortion coefficients when normalizing tracks, as seen in [normalize_tracks](https://github.com/facebookresearch/vggsfm/blob/8efe30e3a31a0048eca819aa14fb4386a99a20aa/vggsfm/models/triangulator.py#L378). This omission can cause slight discrepancies in the normalized values.


Addressing these issues should be straightforward but might require restructuring the code. One potential solution is passing an additional dictionary through all relevant functions to store distortion coefficients using a PyTorch dictionary. Therefore I plan to implement these changes after my current code refactoring.

**Comment by jytime** [comment]
Hi @yzhang-gh @JiamingSuen ,

I’ve fixed the issue in the latest commit. It works well in the examples I’ve tested, but please let me know if you encounter any bugs or issues.
