### ISSUE TITLE
Any plan to release visualization codes?

### ISSUE THREAD

**Issue by leo-frank** [facebookresearch/vggsfm#4]
It's really impressive to see such a solid work on tough SfM problem, it must be the first end-to-end incremental-SfM pipeline!
I have noticed you put some gorgeous images on your paper and project page, I wonder is it allowed to share the visualization codes for poses and point clouds with us?

**Comment by jytime** [comment]
Hi leo,

The visualization code was not written by me.  I could contact the author again and see if there's anything they can do, but I cannot guarantee their response.

**Comment by leo-frank** [comment]
Really thanks for your reply!

**Comment by umiskky** [comment]
> Hi leo,
> 
> The visualization code was not written by me. I could contact the author again and see if there's anything they can do, but I cannot guarantee their response.

Any updates? Can you still share it? This visualization is really beautiful.
