### ISSUE TITLE
is vggsfm support images with folders? 

### ISSUE THREAD

**Issue by huster-wugj** [facebookresearch/vggsfm#42]
great work. is support multi-cam, such as 
image/:
    --cam0
   --cam1
   ...

**Comment by jytime** [comment]
Hi,

To support a multi-camera setup, you can organize your images into separate folders for each camera. Here’s a simple way to restructure your directory:

image_cam0/:
--images

image_cam1/:
--images

This structure makes it easier to run vggsfm. You can use a bash script to automate the reordering of images. After finishing the running, just order them back.
