### ISSUE TITLE
Poor reconstruction on textureless surfaces

### ISSUE THREAD

**Issue by LaFeuilleMorte** [facebookresearch/vggsfm#49]
Hi, thanks for your brilliant work! I was using your HF demo to reconstruct a 1 minute long videos from an indoor scene. But the reconstruction results and the pose were very poor. Especially on the textureless surfaces (floor, wall, ceiling, doors, windows). There're rarely any points on the textureless surfaces. Is there any parameters I can tune to mitigate this problem. My parameter was using the default: 
<img width="370" alt="image" src="https://github.com/user-attachments/assets/f5e0656a-fab2-4fb0-bf2c-77b90eba753f">

Thanks in advance for your reply

**Comment by jytime** [comment]
Hey @LaFeuilleMorte , 

Our hugging face demo is only a very basic illustration. A lot of features have not been supported in our hugging face demo. 

For your case, after you install vggsfm as guided, please try:

'''
python demo.py SCENE_DIR =/YOUR/PATH shared_camera=True camera_type=SIMPLE_RADIAL query_method=aliked

'''

**Comment by LaFeuilleMorte** [comment]
> Hey @LaFeuilleMorte ,
> 
> Our hugging face demo is only a very basic illustration. A lot of features have not been supported in our hugging face demo.
> 
> For your case, after you install vggsfm as guided, please try:
> 
> ```
> python demo.py SCENE_DIR =/YOUR/PATH shared_camera=True camera_type=SIMPLE_RADIAL query_method=aliked
> ```

Thanks for your reply! What's the function of camera type in this method? Would it be ok if I set camera_type=PINHOLE ?

**Comment by jytime** [comment]
Hi now we support

```SIMPLE_ PINHOLE``` and ```SIMPLE_RADIAL```

For ```SIMPLE_ PINHOLE```, the camera is formulated by (f, cx, cy). For ```SIMPLE_RADIAL```, it is (f, cx, cy, k)
