### ISSUE TITLE
how to track images in a fixed order？

### ISSUE THREAD

**Issue by dadwadw233** [facebookresearch/vggsfm#53]
Thanks for the great work！ Is there any way to track the images in a fixed order? To avoid some problems (like symmetry)

**Comment by jytime** [comment]
Hi can you specify this a bit more? Does it mean tracking across frames with knowing the frame order, e.g., like in cotracker? You can easily replace our tracker by cotracker or other tracking methods if you know your input frames are ordered.

Or I just uploaded a script called video_demo, which reconstructs in a sliding window manner. This may also be helpful

**Comment by dadwadw233** [comment]
thanks for your rapid reply, I will try your suggestion 😉 .
I've actually gotten better results on my data by tweaking some of the parameter settings, anyway, thanks for the reply and the fantastic work！
