### ISSUE TITLE
Moving people and objects in the video

### ISSUE THREAD

**Issue by gigasurgeon** [facebookresearch/vggsfm#56]
Thanks for this great work. I am working on a camera path estimation problem. I have a video where people are moving and performing some actions. The camera also is moving. What changes do I need to handle this?

**Comment by jytime** [comment]
Hi @gigasurgeon ,

We support filtering out dynamic objects using masks. Please place the image files in the `SCENE_DIR/images` directory and the corresponding mask files in the `SCENE_DIR/masks` directory. The mask files should have the same base name as the image files. You can refer to how the masks are loaded in the code here:

https://github.com/facebookresearch/vggsfm/blob/00ddb1aac78dea124d7d4994a14b1278f3e3eb08/vggsfm/datasets/demo_loader.py#L225


The masks should be binary, with 1 indicating pixels that should be filtered out (i.e., dynamic pixels) and 0 for pixels that shouldn’t be filtered. These masks can be generated using object detection, video segmentation, or manual labeling. You can refer to the masks from DAVIS dataset as an example.

**Comment by bhack** [comment]
See also our thread at https://github.com/facebookresearch/vggsfm/issues/9

**Comment by gigasurgeon** [comment]
Thank you guys.
