### ISSUE TITLE
CUDA OOM in `test.py`

### ISSUE THREAD

**Issue by jetd1** [facebookresearch/vggsfm#6]
Thanks for releasing this great work!

While running `test.py` following the `README.md`, we encountered CUDA OOM even with bf16 on, when using the default setting. Running with `query_frame_num=1` works fine.

Can you specify the requirements of these tests? I'm using one RTX4090 (24G). Is this OOM expected?

Btw, can you be more specific about the two checkpoints (v1.1 and v1.2)? Are they different in performance?

**Comment by jytime** [comment]
Hi,

Thanks for your interest. I identified a GPU memory bottleneck in the fundamental matrix computation within the `estimate_preliminary_cameras()` function. To address this, I will update the function to use CPU-based OpenCV for fundamental matrix computation or utilize Poselib. This change will significantly reduce GPU memory usage, and I aim to release it soon.

In my tests with a 40GB A100 GPU, even with query_frame_num=1, the results for the IMC dataset were satisfactory. I recommend starting with query_frame_num=1 and increasing to query_frame_num=3 once the new fundamental matrix computation is released.

Regarding the checkpoints:

v1.1: Used to reproduce our claimed performance, trained solely on Megadepth.
v1.2: Designed for demo purposes, trained on a combination of several datasets (e.g., Megadepth + Co3D).
Best regards,

Best,
Jianyuan

**Comment by jetd1** [comment]
Thanks, Jianyuan! I also noticed OOM for longer sequences (100+) I'm working on. This is understandable due to dense corr. 

I'm wondering if you have any suggestions on running on longer sequences and generating a unified final reconstruction? I suppose exporting multiple reconstructions and merge->ba would work, but not sure if this is the optimal solution.

Again thanks for this great work! Any suggestions would be appreciated!

**Comment by jytime** [comment]
Hi,

In our own trials the model can work on 100+ frames if using one 80G A100 GPU, bf16, and some caching (the requirement may be relatively high lol). 

Yes basically the idea would be divide and conquer. Your mentioned strategy is an option. Another one (that we have tried and showed quite good performance) is gradually extending the tracks and hence the reconstruction. For example, (1) pick a starting query frame, (2) predict tracks for N frames, (3) conduct reconstruction, (4) pick another query inside this N frames, (5) use the high-confidence predicted track points as query points and add more keypoints as query points (6) predict tracks for another unseen N frames, (7) local ba and global ba, and then repeat the process. In this process, some tracks disappear and some other tracks are added. This way is quite similar to traditional incremental SfM. The difference between the method you mentioned above is we do not export the reconstruction model.

**Comment by jetd1** [comment]
This is very helpful! Thanks and closing this thread now

**Comment by jytime** [comment]
Hi @jetd1 , in case you may need it, I have updated the code to use Poselib instead of estimate_preliminary_cameras(). With other changes together, this version should only use around 30%-50% GPU memory as before.
