### ISSUE TITLE
Question regarding the order of camera estimator and tracker.

### ISSUE THREAD

**Issue by jk4011** [facebookresearch/vggsfm#62]
First, I want to thank you for your excellent research. I really enjoyed reading your paper.

I do have a question about the camera estimator you used. In the paper, it seems like tracking is done first and then used as input for the camera estimator. But in [the code](https://github.com/facebookresearch/vggsfm/blob/d17db2f3dfa3dc7178f01fb334c0582519a1457d/vggsfm/runners/runner.py#L379-L414), the camera estimator is called first, and then the tracker. Could you clarify where I might be misunderstanding this?

Thank you for your help!

**Comment by jytime** [comment]
Hi,

Thanks for your interest. Please refer to https://github.com/facebookresearch/vggsfm/issues/48
