### ISSUE TITLE
v2 OutOfMemoryError

### ISSUE THREAD

**Issue by scott-vsi** [facebookresearch/vggsfm#63]
I see that you have reduced the memory usage in v2 and provided new guidance on how to adjust the memory usage for different GPUs: https://github.com/facebookresearch/vggsfm?tab=readme-ov-file#9-faqs

I have adjusted both `max_points_num` and `max_tri_points_num`, as well as [`vggsfm/utils/triangulation_helpers.py:MAX_CUSOLVER_STATUS_INVALID_VALUE`](https://github.com/facebookresearch/vggsfm/blob/d17db2f/vggsfm/utils/triangulation_helpers.py#L73)

I can now get through "Global bundle adjustment", but then I hit a `torch.cuda.OutOfMemoryError` when it tries to run Iterative Bundle Adjustment:

```
==============================================================================
Global bundle adjustment
==============================================================================
I20240907 21:37:28.575335 140663715157120 timer.cc:91] Elapsed time: 0.068 [minutes]
Running iterative BA by 1 times
Error executing job with overrides: ['SCENE_DIR=/data/input/', 'camera_type=SIMPLE_RADIAL', 'query_frame_num=4']
Traceback (most recent call last):
  File "/src/demo.py", line 71, in demo_fn
    predictions = vggsfm_runner.run(
  File "/src/vggsfm/runners/runner.py", line 219, in run
    predictions = self.sparse_reconstruct(
  File "/src/vggsfm/runners/runner.py", line 485, in sparse_reconstruct
    ) = self.triangulator(
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/src/vggsfm/models/triangulator.py", line 268, in forward
    ) = iterative_global_BA(
  File "/src/vggsfm/utils/triangulation.py", line 1137, in iterative_global_BA
    valid_poins3D_mask, filtered_inlier_mask = filter_all_points3D(
  File "/src/vggsfm/utils/triangulation_helpers.py", line 189, in filter_all_points3D
    triangles = calculate_triangulation_angle_exhaustive(
  File "/src/vggsfm/utils/triangulation_helpers.py", line 452, in calculate_triangulation_angle_exhaustive
    triangles = calculate_triangulation_angle(
  File "/src/vggsfm/utils/triangulation_helpers.py", line 476, in calculate_triangulation_angle
    ray_length_squared2 = (point3D[None] - proj_center2[:, None]).norm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.92 GiB. GPU 0 has a total capacty of 23.64 GiB of which 3.41 GiB is free. Process 849532 has 20.23 GiB memory in use. Of the allocated memory 8.86 GiB is allocated by PyTorch, and 10.88 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

To get past this error, I folded the calculation in [calculate_triangulation_angle](https://github.com/facebookresearch/vggsfm/blob/d17db2f/vggsfm/utils/triangulation_helpers.py#L473-L498) (as you did in [`vggsfm/utils/triangulation_helpers.py:MAX_CUSOLVER_STATUS_INVALID_VALUE`](https://github.com/facebookresearch/vggsfm/blob/d17db2f/vggsfm/utils/triangulation_helpers.py#L73)), but I was wondering if there was another way (aside from just disabling that step with `BA_iters`)

**Comment by jytime** [comment]
Hi @scott-vsi ,

Thanks for sharing this! Yeah I also just noticed that _filter_all_points3D_ will lead to a problem usually when the frame number is over 300. I think what you are doing is a good practice and I will also provide a _filter_all_points3D_single_chunk_ function to handle this.

Another potential option is using the video runner, although it will require the input frames to be ordered.

**Comment by scott-vsi** [comment]
Thanks for the reply! I will look out for the `filter_all_points3D_single_chunk`. 

Unfortunately, my frames are not ordered.

**Comment by jytime** [comment]
Hi @scott-vsi please let me know if de0e63076cab628bdbe0b922dd177f0df227beb6 works for you.

**Comment by scott-vsi** [comment]
Yes. Thank you! 

Although I did have to disable `demo.yml:center_order` (which you recently enabled by default). Otherwise I hit this OoM error:

```
Traceback (most recent call last):
  File "/src/demo.py", line 71, in demo_fn
    predictions = vggsfm_runner.run(
  File "/src/vggsfm/runners/runner.py", line 228, in run
    predictions = self.sparse_reconstruct(
  File "/src/vggsfm/runners/runner.py", line 406, in sparse_reconstruct
    fmaps_for_tracker = self.track_predictor.process_images_to_fmaps(images)
  File "/src/vggsfm/models/track_predictor.py", line 141, in process_images_to_fmaps
    fmaps = self.coarse_fnet(
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/src/vggsfm/models/track_modules/blocks.py", line 96, in forward
    x = self.conv2(torch.cat([a, b, c, d], dim=1))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.32 GiB. GPU 0 has a total capacty of 23.64 GiB of which 4.27 GiB is free. Process 1915065 has 19.37 GiB memory in use. Of the allocated memory 14.50 GiB is allocated by PyTorch, and 4.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by jytime** [comment]
Weird. Thanks for letting me know. I will test this and see if we need to dis-enable it as default.

**Comment by scott-vsi** [comment]
I only have 24 GB GPU memory, so that constrains things

**Comment by jytime** [comment]
by the way, does the result of the new commit look correct to you?

**Comment by scott-vsi** [comment]
Yes. My SfM still looked correct

**Comment by jytime** [comment]
I might have found the issue. Using center_order slightly increases GPU usage because it clones (or copies) more tensors for temporary usage. While these additional tensors are usually negligible, if GPU usage is already near OOM, this could lead to a problem. You can further reduce the `max_points_num` to mitigate this, but I don’t think it’s necessary as `center_order` typically provides a slight improvement but isn’t crucial in most cases,.
