### ISSUE TITLE
Minor bug report in current code

### ISSUE THREAD

**Issue by TLB-MISS** [facebookresearch/vggsfm#67]
Hi.

First of all, thank you for providing such a great work. 
vggsfm is the most robust (no GT camera)multi-view to 3D I've ever used.

It looks like there's a minor bug in the current code.
If we access variable in [here](https://github.com/facebookresearch/vggsfm/blob/main/vggsfm/runners/runner.py#L579) for reordering while leaving only the valid frames in [here](https://github.com/facebookresearch/vggsfm/blob/main/vggsfm/runners/runner.py#L566), out of index errors will occur. It seems that `center_order` also needs to be filtered.

Thanks.

**Comment by jytime** [comment]
Hi @TLB-MISS ,

Thanks for your kind words! Yeah I see. I am planning to remove ```center_order``` in the future. Would you mind share if you can still get a reliable result without ```center_order=True```?

**Comment by TLB-MISS** [comment]
@jytime 

In fact, there is no difference in quality.

**Comment by jytime** [comment]
Thanks! I have made center_order default as False now, and will remove it in the next version

**Comment by TLB-MISS** [comment]
Thank you for actively refining codes even after the paper was accepted!!
