### ISSUE TITLE
ModuleNotFoundError for 'visdom' and 'imageio' when running demo

### ISSUE THREAD

**Issue by JingruiYu** [facebookresearch/vggsfm#74]
Great work!
I encountered a problem while following the instructions in the README to execute the demo. Here are the steps I performed:
1. Ran source install.sh
2. Executed python -m pip install -e .
3. Tried running python demo.py SCENE_DIR=examples/kitchen

However, I faced the following errors:
- ModuleNotFoundError: No module named 'visdom'
- ModuleNotFoundError: No module named 'imageio'

It might be helpful to include these modules in the install.sh script to prevent such issues.

**Comment by jytime** [comment]
Hi,

Thanks for your interest! While I double checked that they are included in install.sh

https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L28

Can you run this command and see if it work?

**Comment by JingruiYu** [comment]
Thanks for your kindly reply.  This command did not work on my ubuntu22+zsh env,
```
$ pip install omegaconf opencv-python einops visdom tqdm scipy plotly scikit-learn imageio[ffmpeg] gradio trimesh huggingface_hub                                                                                                                                                                                                                               [15:36:32]
zsh: no matches found: imageio[ffmpeg]
(vggsfm_tmp) FAIL: 1
```
I used `pip install imageio` instead.

**Comment by jytime** [comment]
Hey any imageio you can install should work, as long as you can ```import imageio``` .
