### ISSUE TITLE
Questions about load_gt operation.

### ISSUE THREAD

**Issue by strongBrave** [facebookresearch/vggsfm#75]
Thanks for you great work! However, when the `load_gt=True`, there is a function`adjust_camera_to_bbox_crop_()` that is meant to be implemented. In this function, you pass the `anno["focal_length"]` and `anno["principal_point"]` from `pycolmap.reconstruction()` as the intrinsic matrix parameters to be processed.

The issue arises when, within `adjust_camera_to_bbox_crop_()`, the function `_convert_ndc_to_pixels()` is called. This function is designed to convert the focal_length and principal_point from NDC space into pixel space. But, the `anno["focal_length"]` and `anno["principal_point"]` from `pycolmap.reconstruction()` are already in pixel space, not NDC space. Therefore, applying `_convert_ndc_to_pixels()` results in an incorrect transformation, which leads to a bad load_gt operation.

I wonder if I missed some details?, or this implementation is wrong? 
<img src="https://github.com/user-attachments/assets/2a729f6b-2c7f-4e95-af4f-4dbcd0bae68f" width="300"/>
<img src="https://github.com/user-attachments/assets/b2c79d18-005f-4cd5-9166-c574f9902507" width="300"/>

**Comment by jytime** [comment]
Hey Yes! Thanks for pointing out this. I think you are right, this is a bug. For some reason I forgot to include the conversion steps like below to the `demo_loader.py`, sorry about this. I will try to fix this in the next update.

https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/datasets/imc.py#L218-L230

**Comment by strongBrave** [comment]
Right ! If the OPENCV to PT3D step is executed immediately after `pycolmap.reconstruction()`, the subsequent step will be logical.  However, Thanks for your great work.
