### ISSUE TITLE
Regarding the number of matching points

### ISSUE THREAD

**Issue by TLB-MISS** [facebookresearch/vggsfm#76]
Hello.

I have a question about how to increase the number of matching points.
What parameters can I change for this purpose?
The default value of `query_frame_num` is 3 and it seems that it is minimum for triangulation.
Increasing `max_reproj_error` and `init_max_reproj_error` also seems like a possible option.
Could you please let me know of any other parameters I'm missing to increase the number of matching points?

Thanks

**Comment by jytime** [comment]
Hey,

You can increase ```query_frame_num```, ```max_query_pts```, and set ```query_method=aliked+sp+sift```. You can also try ```extra_pt_pixel_interval``` if you wanna something semi-dense.   I would not suggest to increase ```max_reproj_error```.

**Comment by TLB-MISS** [comment]
Thank you so much for your reply! Are there any HPs that regarding with tracker part?

**Comment by jytime** [comment]
Hey I think the HPs above should be enough to provide enough number of matching points. Usually I would not suggest to adjust the tracker part.

**Comment by TLB-MISS** [comment]
Ah, okay. Thanks!
