### ISSUE TITLE
Questions about the calculation of crop_parameters

### ISSUE THREAD

**Issue by strongBrave** [facebookresearch/vggsfm#77]
Thanks for this great work! I am currently studying the code related to establishing a dataset, and I have encountered some confusion regarding the formula used to calculate the crop parameters, particularly the variables `cc` and `crop_width`. These parameters seem to appear rather abruptly, and I am struggling to understand their derivation within the dataset creation process.

Given the importance of this operation to this work, I would greatly appreciate it if you could kindly share any relevant resources that might explain how these parameters are calculated and utilized. Your guidance would be invaluable in helping me move forward with this project.

<img src="https://github.com/user-attachments/assets/59391ff5-df10-4e3d-9f02-561cdac94780" width="300"/>

**Comment by jytime** [comment]
Hey I think we learned cc from 

https://github.com/amyxlase/relpose-plus-plus/blob/b33f7d5000cf2430bfcda6466c8e89bc2dcde43f/relpose/dataset/custom.py#L121

**Comment by strongBrave** [comment]
Thanks for your timely reply. I will try to reach out the author you mentioned to further investigate the question about the calculation about these crop_parameters.

**Comment by jytime** [comment]
Hi @strongBrave, to be honest I think the crop_parameters are not worth much time investigating. In our codebase, usually only the [-4:-2] dimension of crop_params are used. They were just used to record the crop bounding box in the original resolution. You can simply keep this part. 


https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/runners/runner.py#L410C46-L410C51
