### ISSUE TITLE
AttributeError: 'pycolmap._core.Image' object has no attribute 'registered'

### ISSUE THREAD

**Issue by jianghr-shanghaitech** [facebookresearch/vggsfm#78]
(vggsfm) jianghr@DESKTOP-HSN282I:~/vggsfm2/vggsfm$ python video_demo.py SCENE_DIR=examples/phone/
/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
/home/jianghr/vggsfm/dependency/LightGlue/lightglue/lightglue.py:24: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Poselib is available
Poselib is available
PyTorch3d is not available. Please disable visdom.
/home/jianghr/vggsfm2/vggsfm/video_demo.py:18: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="cfgs/", config_name="video_demo")
/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Model Config: query_by_midpoint: true
shared_camera: true
camera_type: SIMPLE_PINHOLE
max_query_pts: 1024
init_window_size: 16
window_size: 8
joint_BA_interval: 6
grid_based_sample: false
model_name: vggsfm_v2_0_0
seed: 0
img_size: 1024
debug: false
center_order: false
mixed_precision: fp16
extract_color: true
filter_invalid_frame: true
comple_nonvis: true
query_frame_num: 3
robust_refine: 2
BA_iters: 1
fine_tracking: true
load_gt: false
viz_visualize: false
gr_visualize: false
fmat_thres: 4.0
max_reproj_error: 4.0
init_max_reproj_error: 4.0
dense_depth: false
avg_pose: true
save_to_disk: true
SCENE_DIR: examples/phone/
resume_ckpt: ckpt/vggsfm_v2_0_0.bin
auto_download_ckpt: false
query_method: aliked
use_poselib: true
shift_point2d_to_original_res: false
make_reproj_video: false
visual_tracks: false
visual_query_points: false
visual_dense_point_cloud: false
query_by_interval: false
concat_extra_points: false
extra_pt_pixel_interval: -1
extra_by_neighbor: -1
MODEL:
  _target_: vggsfm.models.VGGSfM
  TRACK:
    _target_: vggsfm.models.TrackerPredictor
    efficient_corr: false
    COARSE:
      stride: 4
      down_ratio: 2
      FEATURENET:
        _target_: vggsfm.models.BasicEncoder
      PREDICTOR:
        _target_: vggsfm.models.BaseTrackerPredictor
    FINE:
      FEATURENET:
        _target_: vggsfm.models.ShallowEncoder
      PREDICTOR:
        _target_: vggsfm.models.BaseTrackerPredictor
        depth: 4
        corr_levels: 3
        corr_radius: 3
        latent_dim: 32
        hidden_size: 256
        fine: true
        use_spaceatt: false
  CAMERA:
    _target_: vggsfm.models.CameraPredictor
  TRIANGULAE:
    _target_: vggsfm.models.Triangulator

Building VGGSfM
Using cache found in /home/jianghr/.cache/torch/hub/facebookresearch_dinov2_main
/home/jianghr/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
/home/jianghr/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
/home/jianghr/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")
[2024-10-25 09:08:57,474][dinov2][INFO] - using MLP layer as FFN
/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/runner.py:128: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(self.cfg.resume_ckpt)
VGGSfM built successfully
Data size of Sequence: 1
Run Sparse Reconstruction for Scene phone
/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/runner.py:344: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=dtype):
/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/runner.py:418: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=dtype):
Predicting tracks with query_index = 7
Predicting tracks with query_index = 0
Predicting tracks with query_index = 15
Processing non visible frames:  [5, 9, 10, 11]
Predicting tracks with query_index = 5
/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/runner.py:489: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.float32):
/home/jianghr/vggsfm2/vggsfm/vggsfm/models/triangulator.py:74: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.float32):
/home/jianghr/vggsfm2/vggsfm/vggsfm/utils/triangulation.py:653: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(dtype=torch.float32):
frame 0 is out of BA
Error executing job with overrides: ['SCENE_DIR=examples/phone/']
Traceback (most recent call last):
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/utils/tensor_to_pycolmap.py", line 152, in batch_matrix_to_pycolmap
    image.registered = True
AttributeError: 'pycolmap._core.Image' object has no attribute 'registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jianghr/vggsfm2/vggsfm/video_demo.py", line 74, in demo_fn
    predictions = vggsfm_runner.run(
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/video_runner.py", line 129, in run
    init_pred = self.process_initial_window(
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/video_runner.py", line 342, in process_initial_window
    init_pred = self.sparse_reconstruct(
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/runners/runner.py", line 500, in sparse_reconstruct
    ) = self.triangulator(
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jianghr/anaconda3/envs/vggsfm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/models/triangulator.py", line 149, in forward
    ) = init_BA(
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/utils/triangulation.py", line 197, in init_BA
    reconstruction = batch_matrix_to_pycolmap(
  File "/home/jianghr/vggsfm2/vggsfm/vggsfm/utils/tensor_to_pycolmap.py", line 155, in batch_matrix_to_pycolmap
    image.registered = False
AttributeError: 'pycolmap._core.Image' object has no attribute 'registered'

the colmap is 3.11 and the pycolmap is installed as in the colmap

**Comment by jytime** [comment]
Hey please install pycolmap as in https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L41C1-L42C1, i.e., 

```
pip install pycolmap==3.10.0 pyceres
```

**Comment by jianghr-shanghaitech** [comment]
> Hey please install pycolmap as in https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L41C1-L42C1, i.e.,
> 
> ```
> pip install pycolmap==3.10.0 pyceres
> ```

Thank you very much for your quick response. It might be because I didn't notice some changes in the install.sh script and continued using the environment from VGGSfM v1. I will give it a try. Thanks again for your reply and assistance.

**Comment by songsenIng** [comment]
> [嘿，请按照https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L41C1-L42C1](https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L41C1-L42C1)中的说明安装 pycolmap ，即
> 
> ```
> pip install pycolmap==3.10.0 pyceres
> ```

hello, When I installed pycolmap==3.10 and ran demo.py, an error occurred. Could you give me some advice?
```
(vggsfm) PS F:\vggsfm-main> python demo.py SCENE_DIR=examples/kitchen
Traceback (most recent call last):
  File "F:\vggsfm-main\demo.py", line 12, in <module>                                 
    from vggsfm.runners.runner import VGGSfMRunner                                    
  File "F:\vggsfm-main\vggsfm\runners\runner.py", line 12, in <module>                
    import pycolmap                                                                   
ImportError: DLL load failed while importing pycolmap: A dynamic link library (DLL) initialization routine failed.

```

**Comment by tongxinoptica** [comment]
Did you solve this issue?

> > [嘿，请按照https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L41C1-L42C1](https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/install.sh#L41C1-L42C1)中的说明安装 pycolmap ，即
> > ```
> > pip install pycolmap==3.10.0 pyceres
> > ```
> 
> hello, When I installed pycolmap==3.10 and ran demo.py, an error occurred. Could you give me some advice?
> 
> ```
> (vggsfm) PS F:\vggsfm-main> python demo.py SCENE_DIR=examples/kitchen
> Traceback (most recent call last):
>   File "F:\vggsfm-main\demo.py", line 12, in <module>                                 
>     from vggsfm.runners.runner import VGGSfMRunner                                    
>   File "F:\vggsfm-main\vggsfm\runners\runner.py", line 12, in <module>                
>     import pycolmap                                                                   
> ImportError: DLL load failed while importing pycolmap: A dynamic link library (DLL) initialization routine failed.
> ```
