### ISSUE TITLE
Wrong point cloud color when split to chunks

### ISSUE THREAD

**Issue by qiangxinglin** [facebookresearch/vggsfm#84]
I have GPU 3090 with 24GB memory, and want to reconstruct a denser point cloud. So I change `extra_pt_pixel_interval=10` and `concat_extra_points=True`, but encountered Out-of-Memory-Error.  
Then, follow the instructions of [FAQ10](https://github.com/facebookresearch/vggsfm?tab=readme-ov-file#10-faqs), change the `max_points_num=4096*12` and `max_tri_points_num=20480*12`, the demo reconstruction can successfully runned. But the colors of the point clouds are totally messed up. If I increase the `extra_pt_pixel_interval=16` to avoid `Predict tracks in chunks to fit in memory`, the reconstructed point cloud have the correct colors.

Here are the screenshots of two reconstructions:
![image](https://github.com/user-attachments/assets/aa7e4299-6007-4936-bbd3-bb22c2b1ff3e)
![image](https://github.com/user-attachments/assets/f61b612e-9846-461d-b445-8688c6d66419)

**Comment by jytime** [comment]
Hi @qiangxinglin ,

Could you confirm if your run generates the log message: “Cannot save point rgb colors to colmap reconstruction object”? It seems that the reconstruction itself is correct, but there appears to be an issue during the color extraction phase. This might be caused by an order mismatch when converting to the colmap format. I recommend checking the original outputs, specifically ```points3D_rgb``` and ```points3D```, in the code segment below. If necessary, please share some images to reproduce the results and I can have a look. 

https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/models/triangulator.py#L322-L350

**Comment by qiangxinglin** [comment]
Hi @jytime ,
After rerun the construction, it doesn't generate any log message as you have mentioned. Here attached the [reproducible images](https://drive.google.com/file/d/1OMbW1gBwMjbkVB-fV5URy-vzvL6a1lQm/view?usp=sharing) with following project modifications:
1. 163840 to 4096*12
https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/runners/runner.py#L1079
2. 819200 to 20480*12
https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/utils/triangulation_helpers.py#L144
3. 819200 to 20480*12
https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/utils/triangulation.py#L686
4. demo.yaml
  - camera_type: "SIMPLE_RADIAL"
  - shared_camera: True
  - concat_extra_points: True
  - extra_pt_pixel_interval: 10

**Comment by jytime** [comment]
Hey @qiangxinglin ,

Yeah I found that I made a stupid mistake that caused the color mismatch when using extra_pt_pixel_interval and chunking. I’ve addressed this issue in a new commit:

https://github.com/facebookresearch/vggsfm/commit/4eb6fae07ddb30be1a3ac859d9a1173482eb3bbd

Please pull this commit and it should work now. 

Additionally, if you can run the default sparse setting, there’s no need to change `max_points_num`, `max_points_num`, and `max_tri_points_num` with this commit. Just keep them as default should work. I previously wrongly set `all_points_num = images_feed.shape[1] * max_query_pts` but it should be `all_points_num = images_feed.shape[1] * query_points.shape[1]`.


The result will look like:

<img width="456" alt="Screenshot 2024-12-02 at 15 25 18" src="https://github.com/user-attachments/assets/11dd6b96-4b40-40e3-b5f1-b68bf311015e">
