### ISSUE TITLE
Could not find colmap==3.10.0

### ISSUE THREAD

**Issue by sy77777en** [facebookresearch/vggsfm#88]
Hi, your work is excellent! However, when I try to run "pip install pycolmap==3.10.0"
An error occurs:
ERROR: Could not find a version that satisfies the requirement pycolmap==3.10.0 (from versions: 0.4.0, 0.5.0, 0.6.0, 0.6.1)
ERROR: No matching distribution found for pycolmap==3.10.0

**Comment by jytime** [comment]
Hi would this help you?

https://github.com/colmap/colmap/issues/2937

**Comment by sy77777en** [comment]
I'm sorry this does not work for me even though I set pyceres 2.3, but I
could only find pycolmap versions that start with 0.xx . This is odd but I
could still successfully run "python demo.py SCENE_DIR=examples/kitchen". I
think this might be a problem due to my platform.
Thx!

Jianyuan Wang ***@***.***> 于2024年12月2日周一 07:07写道：

**Comment by cqkkqc** [comment]
I can run the code  with" pip install pycolmap pyceres",where my pycolmap is also start with 0.xx .so I guess  the version is not an important problem?

**Comment by sy77777en** [comment]
Yeah, me too. I think this is not important.


crysx00 ***@***.***> 于2024年12月2日周一 20:44写道：
